# Generated by Django 5.2.11 on 2026-02-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
                ('face_text', models.CharField(blank=True, max_length=200)),
                ('body_text', models.CharField(blank=True, max_length=200)),
                ('vibe_text', models.CharField(blank=True, max_length=200)),
                ('face_grade', models.CharField(default='C', max_length=1)),
                ('body_grade', models.CharField(default='C', max_length=1)),
                ('vibe_grade', models.CharField(default='C', max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'slot'), name='unique_user_slot')],
            },
        ),
    ]
