# Generated by Django 6.0.2 on 2026-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userpersona_structured_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
