# Generated by Django 5.2.11 on 2026-04-19 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('판타지', '판타지'), ('무협', '무협'), ('SF', 'SF'), ('로맨스', '로맨스'), ('아포칼립스', '아포칼립스')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('world_setting', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.PositiveSmallIntegerField(default=20)),
                ('personality', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npcs', to='gamebuilder.game')),
            ],
        ),
    ]
