# Generated by Django 6.0.2 on 2026-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='detailed_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='extra_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='prologue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='prompt_template',
            field=models.CharField(blank=True, default='기본 템플릿', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('무협', '무협'), ('판타지', '판타지'), ('SF', 'SF'), ('로맨스', '로맨스'), ('아포칼립스', '아포칼립스'), ('현대', '현대')], max_length=20),
        ),
    ]
