# Generated by Django 5.2.11 on 2026-02-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField(default=0)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('USER_ACTION', '유저행동'), ('USER_DIALOGUE', '유저대사'), ('STORY_TEXT', '스토리텍스트'), ('STORY_IMAGE', '스토리이미지'), ('INFO_PANEL', '정보패널'), ('SUGGESTIONS', '추천답변')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.gamesession')),
            ],
        ),
    ]
