# Generated by Django 5.2.11 on 2026-04-19 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='profiles.profile'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('profile', 'game_id'), name='unique_profile_game'),
        ),
    ]
